config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"

    get "/home", to: "static_pages#home", as: :home
    get "/log-in", to: "sessions#new"
    post "/log-in", to: "sessions#create"
    delete "/log-out", to: "sessions#destroy"

    namespace :admin do
      get "/search_user_by_name", to: "searchs#search_user_by_name"
      post "/add_existing_user_to_course", to: "user_courses#create"
      get "/search_subject_by_name", to: "searchs#search_subject_by_name"
      post "/add_subject_by_name", to: "course_details#create"
      post "/update_subject_status", to: "course_details#update"

      resources :subjects, except: :destroy do
          resources :tasks, only: %i(show edit update)
      end
      resources :courses do
        resources :users, except: :destroy do
          resources :user_subjects, only: %i(index)
        end
      end
      resources :user_courses, only: :create
    end

    post "/update_process_task", to: "process_tasks#update"
    post "/update_user_subject", to: "user_subjects#update"
    resources :courses, only: :show do
      resources :subjects, only: :show do
        resources :tasks, only: :show
      end
    end

    resources :user_subjects, only: %i(create update)
    resources :process_tasks, only: :update
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".app_name"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <li><%= link_to t(".subject"), "#" %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "shared.header.course.link" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.trainer? %>
                <li><%= link_to t("shared.header.course.new"), new_course_path %></li>
              <% end %>
              <li><%= link_to t("shared.header.course.visit"), courses_path %></li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t ".account" %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".profile"), "#" %></li>
              <li><%= link_to t(".setting"), "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), log_out_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".log_in"), log_in_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>